// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// HelloHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) HelloHandler(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_HelloHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HelloHandler'
type MockHandler_HelloHandler_Call struct {
	*mock.Call
}

// HelloHandler is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) HelloHandler(w interface{}, r interface{}) *MockHandler_HelloHandler_Call {
	return &MockHandler_HelloHandler_Call{Call: _e.mock.On("HelloHandler", w, r)}
}

func (_c *MockHandler_HelloHandler_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_HelloHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_HelloHandler_Call) Return() *MockHandler_HelloHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_HelloHandler_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_HelloHandler_Call {
	_c.Run(run)
	return _c
}
