// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/Paste_Bin/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWorkFactory creates a new instance of MockUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWorkFactory {
	mock := &MockUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWorkFactory is an autogenerated mock type for the UnitOfWorkFactory type
type MockUnitOfWorkFactory struct {
	mock.Mock
}

type MockUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWorkFactory) EXPECT() *MockUnitOfWorkFactory_Expecter {
	return &MockUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockUnitOfWorkFactory
func (_mock *MockUnitOfWorkFactory) Begin(ctx context.Context) (repository.TxUnitOfWork, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 repository.TxUnitOfWork
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (repository.TxUnitOfWork, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) repository.TxUnitOfWork); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.TxUnitOfWork)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUnitOfWorkFactory_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockUnitOfWorkFactory_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWorkFactory_Expecter) Begin(ctx interface{}) *MockUnitOfWorkFactory_Begin_Call {
	return &MockUnitOfWorkFactory_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockUnitOfWorkFactory_Begin_Call) Run(run func(ctx context.Context)) *MockUnitOfWorkFactory_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWorkFactory_Begin_Call) Return(txUnitOfWork repository.TxUnitOfWork, err error) *MockUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(txUnitOfWork, err)
	return _c
}

func (_c *MockUnitOfWorkFactory_Begin_Call) RunAndReturn(run func(ctx context.Context) (repository.TxUnitOfWork, error)) *MockUnitOfWorkFactory_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockUnitOfWorkFactory
func (_mock *MockUnitOfWorkFactory) Exec(ctx context.Context) repository.NoTxUnitOfWork {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 repository.NoTxUnitOfWork
	if returnFunc, ok := ret.Get(0).(func(context.Context) repository.NoTxUnitOfWork); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.NoTxUnitOfWork)
		}
	}
	return r0
}

// MockUnitOfWorkFactory_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUnitOfWorkFactory_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWorkFactory_Expecter) Exec(ctx interface{}) *MockUnitOfWorkFactory_Exec_Call {
	return &MockUnitOfWorkFactory_Exec_Call{Call: _e.mock.On("Exec", ctx)}
}

func (_c *MockUnitOfWorkFactory_Exec_Call) Run(run func(ctx context.Context)) *MockUnitOfWorkFactory_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWorkFactory_Exec_Call) Return(noTxUnitOfWork repository.NoTxUnitOfWork) *MockUnitOfWorkFactory_Exec_Call {
	_c.Call.Return(noTxUnitOfWork)
	return _c
}

func (_c *MockUnitOfWorkFactory_Exec_Call) RunAndReturn(run func(ctx context.Context) repository.NoTxUnitOfWork) *MockUnitOfWorkFactory_Exec_Call {
	_c.Call.Return(run)
	return _c
}
