// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/Paste_Bin/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(context1 context.Context, paste *domain.Paste) (*domain.Paste, error) {
	ret := _mock.Called(context1, paste)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Paste
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Paste) (*domain.Paste, error)); ok {
		return returnFunc(context1, paste)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Paste) *domain.Paste); ok {
		r0 = returnFunc(context1, paste)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Paste)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Paste) error); ok {
		r1 = returnFunc(context1, paste)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - paste *domain.Paste
func (_e *MockRepository_Expecter) Create(context1 interface{}, paste interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", context1, paste)}
}

func (_c *MockRepository_Create_Call) Run(run func(context1 context.Context, paste *domain.Paste)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Paste
		if args[1] != nil {
			arg1 = args[1].(*domain.Paste)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(paste1 *domain.Paste, err error) *MockRepository_Create_Call {
	_c.Call.Return(paste1, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context1 context.Context, paste *domain.Paste) (*domain.Paste, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByHash(ctx context.Context, hash string) (*domain.Paste, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *domain.Paste
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Paste, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Paste); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Paste)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockRepository_Expecter) GetByHash(ctx interface{}, hash interface{}) *MockRepository_GetByHash_Call {
	return &MockRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, hash)}
}

func (_c *MockRepository_GetByHash_Call) Run(run func(ctx context.Context, hash string)) *MockRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByHash_Call) Return(paste *domain.Paste, err error) *MockRepository_GetByHash_Call {
	_c.Call.Return(paste, err)
	return _c
}

func (_c *MockRepository_GetByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*domain.Paste, error)) *MockRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, paste *domain.Paste) (*domain.Paste, error) {
	ret := _mock.Called(ctx, paste)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Paste
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Paste) (*domain.Paste, error)); ok {
		return returnFunc(ctx, paste)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Paste) *domain.Paste); ok {
		r0 = returnFunc(ctx, paste)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Paste)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Paste) error); ok {
		r1 = returnFunc(ctx, paste)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - paste *domain.Paste
func (_e *MockRepository_Expecter) Update(ctx interface{}, paste interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, paste)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, paste *domain.Paste)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Paste
		if args[1] != nil {
			arg1 = args[1].(*domain.Paste)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(paste1 *domain.Paste, err error) *MockRepository_Update_Call {
	_c.Call.Return(paste1, err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, paste *domain.Paste) (*domain.Paste, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
