// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/Paste_Bin/internal/util/views_worker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockViewWorker creates a new instance of MockViewWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViewWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViewWorker {
	mock := &MockViewWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockViewWorker is an autogenerated mock type for the ViewWorker type
type MockViewWorker struct {
	mock.Mock
}

type MockViewWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViewWorker) EXPECT() *MockViewWorker_Expecter {
	return &MockViewWorker_Expecter{mock: &_m.Mock}
}

// SendEvent provides a mock function for the type MockViewWorker
func (_mock *MockViewWorker) SendEvent(ctx context.Context, event views.ViewEvent) {
	_mock.Called(ctx, event)
	return
}

// MockViewWorker_SendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEvent'
type MockViewWorker_SendEvent_Call struct {
	*mock.Call
}

// SendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event views.ViewEvent
func (_e *MockViewWorker_Expecter) SendEvent(ctx interface{}, event interface{}) *MockViewWorker_SendEvent_Call {
	return &MockViewWorker_SendEvent_Call{Call: _e.mock.On("SendEvent", ctx, event)}
}

func (_c *MockViewWorker_SendEvent_Call) Run(run func(ctx context.Context, event views.ViewEvent)) *MockViewWorker_SendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 views.ViewEvent
		if args[1] != nil {
			arg1 = args[1].(views.ViewEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViewWorker_SendEvent_Call) Return() *MockViewWorker_SendEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockViewWorker_SendEvent_Call) RunAndReturn(run func(ctx context.Context, event views.ViewEvent)) *MockViewWorker_SendEvent_Call {
	_c.Run(run)
	return _c
}
