// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/Paste_Bin/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Login(ctx context.Context, user *dto.UserRequest) (*dto.APIKeyResponse, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.APIKeyResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UserRequest) (*dto.APIKeyResponse, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UserRequest) *dto.APIKeyResponse); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.APIKeyResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UserRequest) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - user *dto.UserRequest
func (_e *MockUseCase_Expecter) Login(ctx interface{}, user interface{}) *MockUseCase_Login_Call {
	return &MockUseCase_Login_Call{Call: _e.mock.On("Login", ctx, user)}
}

func (_c *MockUseCase_Login_Call) Run(run func(ctx context.Context, user *dto.UserRequest)) *MockUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UserRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_Login_Call) Return(aPIKeyResponse *dto.APIKeyResponse, err error) *MockUseCase_Login_Call {
	_c.Call.Return(aPIKeyResponse, err)
	return _c
}

func (_c *MockUseCase_Login_Call) RunAndReturn(run func(ctx context.Context, user *dto.UserRequest) (*dto.APIKeyResponse, error)) *MockUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Registration provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Registration(ctx context.Context, user *dto.UserRequest) (*dto.UserResponse, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Registration")
	}

	var r0 *dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UserRequest) (*dto.UserResponse, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.UserRequest) *dto.UserResponse); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.UserRequest) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_Registration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Registration'
type MockUseCase_Registration_Call struct {
	*mock.Call
}

// Registration is a helper method to define mock.On call
//   - ctx context.Context
//   - user *dto.UserRequest
func (_e *MockUseCase_Expecter) Registration(ctx interface{}, user interface{}) *MockUseCase_Registration_Call {
	return &MockUseCase_Registration_Call{Call: _e.mock.On("Registration", ctx, user)}
}

func (_c *MockUseCase_Registration_Call) Run(run func(ctx context.Context, user *dto.UserRequest)) *MockUseCase_Registration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.UserRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.UserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_Registration_Call) Return(userResponse *dto.UserResponse, err error) *MockUseCase_Registration_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUseCase_Registration_Call) RunAndReturn(run func(ctx context.Context, user *dto.UserRequest) (*dto.UserResponse, error)) *MockUseCase_Registration_Call {
	_c.Call.Return(run)
	return _c
}
